services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=PsiFirm'
      - 'POSTGRES_PASSWORD=PsiFirm-db'
      - 'POSTGRES_USER=PsiFirm-root'
    ports:
      - '5433:5432'
    volumes:
      - pg_sie_data:/data/postgres
volumes:
  pg_sie_data: